spring:
    profiles:
        active: development
---
spring:
    profiles: development
    data:
        mongodb:
            host: 127.0.0.1
            port: 27017
---
spring:
    profiles: container
    data:
        mongodb:
            host: ${MONGODB_PORT_27017_TCP_ADDR}
            port: 27017
